version: '3.9'
services:  
  moodle:
    build:
      context: ./.docker
      dockerfile: Dockerfile    
    working_dir: /var/www/html/moodle
    ports:
      - 8000:80    
    volumes:
      - ./moodle:/var/www/html/moodle            
      - ./moodle_data:/var/www/html/moodledata
      - ./.docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf     
      - ./.docker/custom-php-config.ini:/usr/local/etc/php/conf.d/custom.ini
    entrypoint: [ "/bin/sh" , "/opt/entrypoint.sh" ]  
    command: apache2-foreground
    env_file:
      - ./.env   
    environment:
      TZ: America/Sao_Paulo  
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1          
    tty: true
    links:
      - db
    depends_on:
      - db    
  db:
    image: postgres:11.1-alpine    
    ports:
      - 5432:5432    
    tty: true    
    volumes:      
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'moodle'
      POSTGRES_PASSWORD: 'moodle'
      POSTGRES_DB: 'moodle'
      TZ: America/Sao_Paulo  